use serde_json::{json, Value};
use tauri::State;

use crate::{
    now_iso, redclaw_root, resolve_manuscript_path, slug_from_relative_path, write_text_file,
    AppState,
};

pub(crate) fn detect_redclaw_artifact_kind(prompt: &str, source_label: &str) -> &'static str {
    let lower = prompt.to_lowercase();
    if lower.contains("save-copy") || lower.contains("文案包") {
        "copy"
    } else if lower.contains("save-image") || lower.contains("配图") || lower.contains("封面") {
        "image"
    } else if lower.contains("save-retro") || lower.contains("复盘") {
        "retro"
    } else if source_label.contains("scheduled") || source_label.contains("long-cycle") {
        "automation"
    } else {
        "run"
    }
}

pub(crate) fn save_redclaw_outputs(
    state: &State<'_, AppState>,
    kind: &str,
    session_id: &str,
    prompt: &str,
    response: &str,
    source_label: &str,
) -> Result<Vec<Value>, String> {
    let mut artifacts = Vec::new();
    let timestamp = now_iso();
    let slug = slug_from_relative_path(&format!("{session_id}-{source_label}-{timestamp}"));

    let run_path = redclaw_root(state)?.join("runs").join(format!("{slug}.md"));
    let run_body = format!(
        "# RedClaw Run\n\n- Source: {}\n- Session: {}\n- Time: {}\n\n## Prompt\n\n{}\n\n## Response\n\n{}\n",
        source_label, session_id, timestamp, prompt, response
    );
    write_text_file(&run_path, &run_body)?;
    artifacts.push(json!({
        "kind": "run-log",
        "path": run_path.display().to_string(),
        "label": "RedClaw run log",
    }));

    match kind {
        "copy" => {
            let manuscript_relative = format!("redclaw/{}.md", slug);
            let manuscript_path = resolve_manuscript_path(state, &manuscript_relative)?;
            let manuscript_body = format!(
                "# RedClaw Copy Package\n\n> Generated by: {}\n\n{}",
                source_label, response
            );
            write_text_file(&manuscript_path, &manuscript_body)?;
            artifacts.push(json!({
                "kind": "manuscript",
                "path": manuscript_path.display().to_string(),
                "relativePath": manuscript_relative,
                "label": "Copy package manuscript",
            }));
        }
        "retro" => {
            let retro_path = redclaw_root(state)?
                .join("retro")
                .join(format!("{slug}.md"));
            let retro_body = format!(
                "# RedClaw Retro\n\n> Generated by: {}\n\n{}",
                source_label, response
            );
            write_text_file(&retro_path, &retro_body)?;
            artifacts.push(json!({
                "kind": "retro",
                "path": retro_path.display().to_string(),
                "label": "Retro note",
            }));
        }
        "image" => {
            let prompt_path = redclaw_root(state)?
                .join("images")
                .join(format!("{slug}.md"));
            let prompt_body = format!(
                "# RedClaw Image Prompt Pack\n\n> Generated by: {}\n\n{}",
                source_label, response
            );
            write_text_file(&prompt_path, &prompt_body)?;
            artifacts.push(json!({
                "kind": "image-prompts",
                "path": prompt_path.display().to_string(),
                "label": "Image prompt pack",
            }));
        }
        _ => {}
    }

    Ok(artifacts)
}

#[cfg(test)]
mod tests {
    use super::detect_redclaw_artifact_kind;

    #[test]
    fn detects_redclaw_artifact_kind_from_prompt_and_source() {
        assert_eq!(
            detect_redclaw_artifact_kind("请 save-copy 输出文案", "manual"),
            "copy"
        );
        assert_eq!(
            detect_redclaw_artifact_kind("生成封面配图", "manual"),
            "image"
        );
        assert_eq!(
            detect_redclaw_artifact_kind("做一次复盘", "manual"),
            "retro"
        );
        assert_eq!(
            detect_redclaw_artifact_kind("常规执行", "scheduled-task"),
            "automation"
        );
        assert_eq!(detect_redclaw_artifact_kind("常规执行", "manual"), "run");
    }
}
