import type { BridgeCore, Listener } from '../types';

export function createManuscriptsBridge(core: BridgeCore) {
  return {
    manuscripts: {
      list: <T = unknown>() => core.invokeChannel('manuscripts:list') as Promise<T>,
      read: <T = unknown>(filePath: string) => core.invokeChannel('manuscripts:read', filePath) as Promise<T>,
      save: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:save', payload) as Promise<T>,
      createFile: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:create-file', payload) as Promise<T>,
      createFolder: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:create-folder', payload) as Promise<T>,
      rename: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:rename', payload) as Promise<T>,
      move: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:move', payload) as Promise<T>,
      delete: <T = unknown>(targetPath: string) => core.invokeChannel('manuscripts:delete', targetPath) as Promise<T>,
      attachExternalFiles: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:attach-external-files', payload) as Promise<T>,
      getPackageState: <T = unknown>(targetPath: string) => core.invokeChannel('manuscripts:get-package-state', targetPath) as Promise<T>,
      generateRemotionScene: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:generate-remotion-scene', payload) as Promise<T>,
      saveRemotionScene: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:save-remotion-scene', payload) as Promise<T>,
      pickExportPath: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:pick-export-path', payload) as Promise<T>,
      renderRemotionVideo: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:render-remotion-video', payload) as Promise<T>,
      getWriteProposal: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:get-write-proposal', payload) as Promise<T>,
      acceptWriteProposal: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:accept-write-proposal', payload) as Promise<T>,
      rejectWriteProposal: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:reject-write-proposal', payload) as Promise<T>,
      confirmPackageScript: <T = unknown>(payload: { filePath: string }) => core.invokeChannel('manuscripts:confirm-package-script', payload) as Promise<T>,
      getLayout: <T = unknown>() => core.invokeChannel('manuscripts:get-layout') as Promise<T>,
      saveLayout: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:save-layout', payload) as Promise<T>,
      saveRichpostCardPreview: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:save-richpost-card-preview', payload) as Promise<T>,
      generatePackageHtml: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:generate-package-html', payload) as Promise<T>,
      setRichpostTheme: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:set-richpost-theme', payload) as Promise<T>,
      renderRichpostPages: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:render-richpost-pages', payload) as Promise<T>,
      setLongformLayoutPreset: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:set-longform-layout-preset', payload) as Promise<T>,
      upgradeToPackage: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:upgrade-to-package', payload) as Promise<T>,
      applyRichpostPagePlan: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:apply-richpost-page-plan', payload) as Promise<T>,
      saveEditorProject: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:save-editor-project', payload) as Promise<T>,
      getEditorRuntimeState: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:get-editor-runtime-state', payload) as Promise<T>,
      updateEditorRuntimeState: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:update-editor-runtime-state', payload) as Promise<T>,
      undoEditorProject: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:undo-editor-project', payload) as Promise<T>,
      redoEditorProject: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:redo-editor-project', payload) as Promise<T>,
      updatePackageTrackUi: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:update-package-track-ui', payload) as Promise<T>,
      updatePackageSceneUi: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:update-package-scene-ui', payload) as Promise<T>,
      addPackageTrack: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:add-package-track', payload) as Promise<T>,
      movePackageTrack: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:move-package-track', payload) as Promise<T>,
      deletePackageTrack: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:delete-package-track', payload) as Promise<T>,
      addPackageClip: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:add-package-clip', payload) as Promise<T>,
      insertPackageClipAtPlayhead: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:insert-package-clip-at-playhead', payload) as Promise<T>,
      insertPackageSubtitleAtPlayhead: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:insert-package-subtitle-at-playhead', payload) as Promise<T>,
      insertPackageTextAtPlayhead: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:insert-package-text-at-playhead', payload) as Promise<T>,
      updatePackageClip: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:update-package-clip', payload) as Promise<T>,
      deletePackageClip: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:delete-package-clip', payload) as Promise<T>,
      splitPackageClip: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:split-package-clip', payload) as Promise<T>,
      transcribePackageSubtitles: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:transcribe-package-subtitles', payload) as Promise<T>,
      saveRichpostCustomTheme: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:save-richpost-custom-theme', payload) as Promise<T>,
      createRichpostCustomTheme: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:create-richpost-custom-theme', payload) as Promise<T>,
      previewRichpostThemeDraft: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:preview-richpost-theme-draft', payload) as Promise<T>,
      getRichpostThemePreviews: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:get-richpost-theme-previews', payload) as Promise<T>,
      deleteRichpostCustomTheme: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:delete-richpost-custom-theme', payload) as Promise<T>,
      uploadRichpostThemeBackground: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:upload-richpost-theme-background', payload) as Promise<T>,
      pickRichpostExportPath: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:pick-richpost-export-path', payload) as Promise<T>,
      saveRichpostExportArchive: <T = unknown>(payload: Record<string, unknown>) => core.invokeChannel('manuscripts:save-richpost-export-archive', payload) as Promise<T>,
      onRenderProgress: (listener: Listener) => core.on('manuscripts:render-progress', listener),
      offRenderProgress: (listener: Listener) => core.off('manuscripts:render-progress', listener),
      onWriteProposal: (listener: Listener) => core.on('manuscripts:write-proposal', listener),
      offWriteProposal: (listener: Listener) => core.off('manuscripts:write-proposal', listener),
    },
  };
}
